---
title: "plot"
author: "Jingyou Rao"
date: "7/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

# sample_size
```{r}
root = "./sample_size"
file = list.files(root)
h2g_hess = NULL
for (i in 1:length(file)) {
  h2g = read.csv(paste(root, file[i], sep = "/"), header = FALSE)
  temp = strsplit(file[i], "_")[[1]][3]
  ss = substr(temp, 1, nchar(temp)-4)
  h2g$V2 = ss
  h2g_hess = rbind(h2g_hess, h2g)
}
rm(i, root, file, ss, temp, h2g)
colnames(h2g_hess) <- c("h2g_pred", "sample_size")
```

box plots + jitter points, then a horizontal line at the truth

```{r}
h2g_hess$sample_size <- ordered(h2g_hess$sample_size, 
                                levels = c("20", "50", "100", "200", "500"))
ggplot(h2g_hess, aes(x=sample_size, y=h2g_pred)) + 
  geom_boxplot(na.rm = TRUE) +
  geom_jitter(na.rm = TRUE) +
  geom_hline(yintercept = 0.08, linetype="dashed", color = "red", size = 1.5) +
  labs(title = "Heritability Prediction (HESS) vs. Sample Size",
       x = "Sample Size", y = "Gene Heritability Prediction")

ggplot(h2g_hess[h2g_hess$sample_size%in%c("100","200","500"), ], 
       aes(x=sample_size, y=h2g_pred)) + 
  geom_boxplot(na.rm = TRUE) +
  geom_jitter(na.rm = TRUE) +
  geom_hline(yintercept = 0.08, linetype="dashed", color = "red", size = 1.5) +
  labs(title = "Heritability Prediction (HESS) vs. Sample Size",
       x = "Sample Size", y = "Gene Heritability Prediction")
```

# formula_HESS
```{r}
root <- "./formula_hess/100"
file <- list.files(root)[2:4]
h2g_formula <- NULL
for (i in 1:length(file)) {
  h2g <- read.csv(paste(root, file[i], sep = "/"), header = FALSE)
  h2g$V2 <- file[i]
  h2g_formula <- rbind(h2g_formula, h2g)
}
rm(i, root, file, h2g)
h2g_formula$sample_size <- 100
colnames(h2g_formula) <- c("h2g_pred", "method", "sample_size")
```

```{r}
root <- "./formula_hess/200"
file <- list.files(root)[2:4]
for (i in 1:length(file)) {
  h2g <- read.csv(paste(root, file[i], sep = "/"), header = FALSE)
  h2g$method <- file[i]
  h2g$sample_size <- 200
  colnames(h2g) <- c("h2g_pred", "method", "sample_size")
  h2g_formula <- rbind(h2g_formula, h2g)
}
rm(h2g, file, i, root)
```

```{r}
root <- "./formula_hess/500"
file <- list.files(root)[2:4]
for (i in 1:length(file)) {
  h2g <- read.csv(paste(root, file[i], sep = "/"), header = FALSE)
  h2g$method <- file[i]
  h2g$sample_size <- 500
  colnames(h2g) <- c("h2g_pred", "method", "sample_size")
  h2g_formula <- rbind(h2g_formula, h2g)
}
rm(h2g, file, i, root)
```

```{r}
h2g_formula$method <- as.factor(h2g_formula$method)
levels(h2g_formula$method) <- c("formula_gene", "formula_isoform", "HESS")
```

```{r}
ggplot(h2g_formula[h2g_formula$sample_size==100, ], aes(x=method, y=h2g_pred)) + 
  geom_boxplot(na.rm = TRUE) +
  geom_jitter(na.rm = TRUE) +
  geom_hline(yintercept = 0.08, linetype="dashed", color = "red", size = 1.5) +
  labs(title = "Heritability Prediction with Different Method", subtitle = "Sample Size: 100",
       x = "Method", y = "Gene Heritability Prediction")

ggplot(h2g_formula[h2g_formula$sample_size==200, ], aes(x=method, y=h2g_pred)) + 
  geom_boxplot(na.rm = TRUE) +
  geom_jitter(na.rm = TRUE) +
  geom_hline(yintercept = 0.08, linetype="dashed", color = "red", size = 1.5) +
  labs(title = "Heritability Prediction with Different Method", subtitle = "Sample Size: 200",
       x = "Method", y = "Gene Heritability Prediction")

ggplot(h2g_formula[h2g_formula$sample_size==500, ], aes(x=method, y=h2g_pred)) + 
  geom_boxplot(na.rm = TRUE) +
  geom_jitter(na.rm = TRUE) +
  geom_hline(yintercept = 0.08, linetype="dashed", color = "red", size = 1.5) +
  labs(title = "Heritability Prediction with Different Method", subtitle = "Sample Size: 500",
       x = "Method", y = "Gene Heritability Prediction")

```

```{r}
ggplot(h2g_formula, aes(x=method, y=h2g_pred, fill = as.factor(sample_size))) + 
  geom_boxplot(na.rm = TRUE) +
  geom_jitter(na.rm = TRUE, size = 0.5, aes(colour = as.factor(sample_size)),
              position = position_jitterdodge()) +
  geom_hline(yintercept = 0.08, linetype="dashed", color = "red", size = 1.5) +
  labs(title = "Heritability Prediction with Different Methods",
       x = "Method", y = "Gene Heritability Prediction", fill = "Sample Size") +
  guides(colour = FALSE)
```

