---
title: "plot_0717"
author: "Jingyou Rao"
date: "7/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

# HESS Formula
```{r}
root <- "./GREML"
file <- list.files(root)[3:5]
h2g_formula <- NULL
for (i in 1:length(file)) {
  h2g <- read.csv(paste(root, file[i], sep = "/"), header = FALSE)
  h2g$V2 <- file[i]
  h2g_formula <- rbind(h2g_formula, h2g)
}
rm(i, root, file, h2g)
colnames(h2g_formula) <- c("h2g_pred", "method")
```

```{r}
h2g_formula$method <- as.factor(h2g_formula$method)
levels(h2g_formula$method) <- c("formula_gene", "formula_isoform", "HESS")
```

# GREML
```{r}
root <- "./GREML/results"
file <- list.files(root)
file <- file[grep("(*)1.cis.hsq", file)]
h2g_greml <- NULL
for (i in 1:length(file)) {
  h2g <- read.delim(paste(root, file[i], sep = "/"), header = FALSE)[5, 2:3]
  h2g_mean <- h2g[1, 1]
  h2g_mean <- as.numeric(levels(h2g_mean)[h2g_mean])
  h2g_var <- h2g[1, 2]
  h2g_var <- as.numeric(levels(h2g_var)[h2g_var])
  h2g_greml <- rbind(h2g_greml, c(h2g_mean, h2g_var))
}
h2g_greml <- data.frame(h2g_greml)
colnames(h2g_greml) <- c("h2g_pred", "var")
h2g_greml$method <- "GREML"
rm(i, root, h2g_var, h2g_mean, file, h2g)
```

# total plot
```{r}
h2g_total <- rbind(h2g_formula, h2g_greml[, c(1,3)])
```

```{r}
ggplot(h2g_total[-c(31,131,231,331), ], aes(x=method, y=h2g_pred)) + 
  geom_boxplot(na.rm = TRUE) +
  geom_jitter(na.rm = TRUE) +
  geom_hline(yintercept = 0.08, linetype="dashed", color = "red", size = 1.5) +
  labs(title = "Heritability Prediction with Different Methods", subtitle = "Sample Size: 100",
       x = "Method", y = "Gene Heritability Prediction")
```

# GREML plot
```{r}
ggplot(h2g_greml, aes(x=1:100, y=h2g_pred)) +
  geom_point() +
  geom_hline(aes(yintercept = 0.08, linetype="True Value"), color = "red", size = 1.5) +
  geom_hline(aes(yintercept = mean(h2g_pred), linetype="Mean of Estimation"), 
             color = "blue", size = 1.5) +
  labs(title = "Heritability Prediction GREML w/ Variance", subtitle = "Sample Size: 100",
       x = "Simulation", y = "Gene Heritability Prediction") +
  geom_errorbar(aes(ymin=h2g_pred-var, ymax=h2g_pred+var)) +
  scale_linetype_manual(name = NULL, values = c(2, 2), 
                      guide = guide_legend(override.aes = list(color = c("blue", "red"))))
  
```


